id: A9AA59772
base_file: f2816.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.866342
  last_modified_at: 2022-06-17 13:56:58.866345
