id: A9AA59772
base_file: f4BDE.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.879993
  last_modified_at: 2022-06-17 13:56:58.879996
