id: A9AA59772
base_file: f4267.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.875242
  last_modified_at: 2022-06-17 13:56:58.875245
