id: A9AA59772
base_file: fBBD9.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.954993
  last_modified_at: 2022-06-17 13:56:58.954995
