id: A9AA59772
base_file: f3146.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.870239
  last_modified_at: 2022-06-17 13:56:58.870241
