id: A9AA59772
base_file: fFCAE.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.977298
  last_modified_at: 2022-06-17 13:56:58.977301
