id: A9AA59772
base_file: f9F7D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.945725
  last_modified_at: 2022-06-17 13:56:58.945728
