id: A9AA59772
base_file: f4D42.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.882763
  last_modified_at: 2022-06-17 13:56:58.882766
