id: A9AA59772
base_file: f59C8.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.887256
  last_modified_at: 2022-06-17 13:56:58.887259
