id: A9AA59772
base_file: f2BE3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.867828
  last_modified_at: 2022-06-17 13:56:58.867831
