id: A9AA59772
base_file: f8918.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 13:56:58.905847
  last_modified_at: 2022-06-17 13:56:58.905850
